name: cell_calendar
description: Modern calendar widget with useful features. Enables to develop well designed calendar in a moment. Inspired by the UI of Google calendar.
version: 0.8.0
homepage: https://github.com/santa112358/cell_calendar

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.3"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
